### ISSUE TITLE
这个client 必须是 mut 的 是必须的吗？

### ISSUE THREAD

**Issue by ansjsun** [smallnest/rpcx-rs#3]
![image](https://user-images.githubusercontent.com/1221947/72035934-462c8600-32d4-11ea-9683-7aac1d3c3fa2.png)
这样很不方便复用，不过我rust 不太熟悉。我理解的对吗

**Comment by smallnest** [comment]
是

**Comment by ansjsun** [comment]
那这样没法用啊，每一个请求都创建一个client？

**Comment by smallnest** [comment]
建议长讨论在qq群中讨论。

`&mut`也不是每个请求必须创建，看例子调用n次。

**Comment by ansjsun** [comment]
qq 群号码多少， 或者微信号码 我加你额
